name: Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        haxe-version: [4.2.2]
        target: [html5]

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build (${{ matrix.target }}, ${{ matrix.os }})
      run: |
        node Kha/make ${{ matrix.target }} --compile
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build/html5