name: Build Khatile

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        target: [html5]
    steps:
    
    - name: try to restore kha from cache
      uses: actions/cache/restore@v3
      id: cache-kha
      with:
        path: Kha
        key: kha

    - name: checkout khatile & dependencies submodules
      uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: cache Kha
      uses: actions/cache@v3
      with:
        path: ~/Kha
        key: kha
        restore-keys: |
          kha

    - name: try to restore koui from cache
      uses: actions/cache/restore@v3
      id: cache-koui
      with:
        path: Subprojects/koui
        key: koui

    - name: cache test / checkout koui (gitlab)
      if: steps.cache-koui.outputs.cache-hit != 'true'
      run: rm -rf Subprojects/koui && git clone "https://gitlab.com/koui/koui.git" Subprojects/koui

    - name: cache koui
      uses: actions/cache@v3
      with:
        path: ~/Subprojects/koui
        key: koui
        restore-keys: |
          koui

    - name: setup ffmpeg
      uses: FedericoCarboni/setup-ffmpeg@v2
      id: setup-ffmpeg

    - name: create build dir
      run: |
        mkdir build && mkdir build/html5

    #- name: export ogg
    #  uses: canastro/copy-file-action@master
    #  with:
    #    source: "Assets/sound.ogg"
    #    target: "build/html5/sound.ogg"

    - name: build ${{ matrix.target }}
      run: |
        node Kha/make ${{ matrix.target }} --compile --ffmpeg ${{steps.setup-ffmpeg.outputs.ffmpeg_path}}

    - name: deploy to github pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build/html5
